// This file is Copyright its original authors, visible in version control
// history.
//
// This file is licensed under the Apache License, Version 2.0 <LICENSE-APACHE
// or http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your option.
// You may not use this file except in accordance with one or both of these
// licenses.

//! Tests that test-standing up a dance of credentials authentication between
//! a CommitManager and an IssuanceManager, acceptance and rejection cases.

#[test]
fn test_credential_policy_dance() {
	// Test CredentialPolicy generated by IssuanceManager is accepted
	// by CommitManager
}

#[test]
fn test_onchain_collateral_acceptance() {
	// Test CollateralAsset::OnchainPayment
	// The on-chain payment destination should be conform to the
	// CredentialPolicy's announced invoice issuer. Reject otherwise.
	//
	// The on-chain payment for the quantity of credentials requested
	// should be conform to the CredentialPolicy's ratio. Reject otherwise.
	//
	// The type of blinded credentials should be supported by the node.
	// Reject otherwise.
}

#[test]
fn test_offchain_collateral_acceptance() {
	// Test CollateralAsset::OffchainPayment
	// The off-chain payment payee should be conform to the
	// CredentialPolicy's announced invoice isuser. Reject otherwise.
	//
	// The off-chain payment for the quantity of credentials requested
	// should be conform to the CredentialPolicy's ratio. Reject otherwise.
	//
	// The type of blinded credentials should be supported by the node.
	// Reject otherwise.
}
